### ISSUE TITLE
API9版本radar可以安装 但是功能几乎全部失效

### ISSUE THREAD

**Issue by zxwqwq** [emptyset0/Radar_akira0245#2]
卫月版本9.0.0.22 Radar版本2.0.4.1 在仅安装Radar的情况下 3D覆盖几乎全部失效 2D覆盖也仅生效了一个辅助圈

**Comment by emptyset0** [comment]
是“只显示可选中物体”选项出了问题，正在修
暂时可以取消该选项的勾选，大概能正常用

**Comment by emptyset0** [comment]
修好了
